Repository eagle-fox/dawMp, pull requests merged in 2024-02, with the labels that each got.

#35 Solucionado espacio de trabajo ausente en idea #11
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  docker/Dockerfile-php
Labels: bug

#38 Dev docker
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  back/api/composer.lock
  docker-compose.prod.yml
  docker-compose.yml
  docker/Dockerfile-php
Labels: bug

#39 #26 Añadido nuevo sistema de idiomas + Login basico
  front/src/components/NavBar.vue
  front/src/locales/de.js
  front/src/locales/en.js
  front/src/locales/es.js
  front/src/locales/gl.js
  front/src/router/index.js
  front/src/views/Home.vue
  front/src/views/Login.vue
Labels: enhancement

#41 Integración #11 docs
  README.md
Labels: documentation

#46 #28 prototipo de User en la API para testing
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  back/api/app/controllers/UsersController.php
  back/api/app/controllers/Utils.php
  back/api/app/routes/mapping.md
  back/api/app/routes/rutas.http
  back/api/composer.json
  back/api/composer.lock
  db/init.sql
Labels: enhancement

#50 #28 Especificaciones RC de la API
  back/api/app/controllers/DemoController.php
  back/api/app/controllers/IotDataController.php
  back/api/app/controllers/IotDevicesController.php
  back/api/app/middlewares/MiddlewareUser.php
  back/api/app/models/IotDevice.php
  back/api/app/models/User.php
  db/init.sql
  demoData.iml
  demoData/go.mod
  demoData/go.sum
  demoData/main.go
  docker/Dockerfile-php-zts
  iot/demoData/.idea/.gitignore
  iot/demoData/.idea/modules.xml
  iot/demoData/.idea/vcs.xml
Labels: enhancement
